[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisor.log
logfile_maxbytes=10MB
logfile_backups=10
childlogdir=/var/log/supervisor

[program:apache]
command=apachectl -D "FOREGROUND" -k start
redirect_stderr=true
autorestart=true
startretries=999999

[program:satis-updater]
command=/bin/bash /root/update-satis.sh %(ENV_REFRESH_SLEEP_PERIOD)s
redirect_stderr=true
autorestart=true
startretries=999999

[supervisorctl]
